remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Yu Minematsu
logo: /assets/img/me.JPG
description: MS Computer Science Student at New York University, Courant
google_analytics: G-P8QRG4ZTP2


